[project]
name = "deepseek-reverse-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "asgiref>=3.11.1",
    "flask>=3.1.3",
    "flask-cors>=6.0.2",
    "openai>=2.37.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "uvicorn>=0.47.0",
]
